name: gainz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  lottie: ^3.1.2
  neopop: ^1.0.2
  responsive_sizer: ^3.3.1
  toastification: ^2.0.0
  logger: ^2.4.0
  google_mlkit_pose_detection: ^0.12.0
  camera: ^0.10.6
  animated_flip_counter: ^0.3.4
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lottiefiles/
    - assets/audio/
