// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1YzJVuDUOozUsJ8oOgPYDL54mbNViDQ',
    appId: '1:233308871814:android:4d9119e3559d7eef8c0507',
    messagingSenderId: '233308871814',
    projectId: 'gainz-interview',
    storageBucket: 'gainz-interview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT3iikoVItHOq3PQa9jHnLokYBo51jbOo',
    appId: '1:233308871814:ios:c793ae1f1f32f1178c0507',
    messagingSenderId: '233308871814',
    projectId: 'gainz-interview',
    storageBucket: 'gainz-interview.appspot.com',
    androidClientId: '233308871814-nsq3qiqv4ehqmuej0k7ul9csjf4qcv5l.apps.googleusercontent.com',
    iosClientId: '233308871814-d95c1bmajp0rgj2tb4opetfntttskfti.apps.googleusercontent.com',
    iosBundleId: 'com.example.gainz',
  );

}